// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owattfjgpfpydbofnbee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YXR0ZmpncGZweWRib2ZuYmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mjk1OTIsImV4cCI6MjA2NTIwNTU5Mn0.NkPorjhih12rfnblxsHEqEF6StZp0SKOWRDi4wwthkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);